version: "3.9"
# todo: змінити конфіги з '%skeleton%' на щось інше
# - docker compose up;
# - ds wp

networks:
  wp_form:

services:
  wp_mysql:
    image: mysql:8.0
    container_name: mysql8_skeleton
    restart: unless-stopped
    networks:
      - wp_form
    ports:
      - '3306:3306'
    volumes:
      - ./.build/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wp_form
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  # http://localhost:8080/
  wordpress:
    image: wordpress:latest
    container_name: wp_skeleton
    depends_on:
      - wp_mysql
    links:
      - wp_mysql
    restart: unless-stopped
    networks:
      - wp_form
    ports:
      - '8080:80'
    environment:
      WORDPRESS_DB_HOST: wp_mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wp_form
      WORDPRESS_DEBUG: 1
    volumes:
      # цей volume для того, щоб wordpress з цієї папки брати і ставити в інтерпретатор, на сам сервер
      # тепер можемо вносити зміни в теми або плагіни і вони будуть доступні в контейнері без його перезапуску
      - ./.build/wordpress:/var/www/html
      # монтуємо теми в контейнер
#      - ./src/themes/mytheme/:/var/www/html/wp-content/themes/mytheme
      # монтуємо плагіни в контейнер
#      - ./src/plugin/:/var/www/html/wp-content/plugins/my-core
      # монтуємо конфіги для php в контейнер
      - ./src/php-custom.ini:/usr/local/etc/php/conf.d/custom.ini

  # http://localhost:8181/
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_skeleton
    depends_on:
      - wp_mysql
    links:
      - wp_mysql
    networks:
      - wp_form
    ports:
      - '8181:80'
    environment:
      MYSQL_USERNAME: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
      PMA_HOST: wp_mysql
    restart: unless-stopped
